spring.application.name=PruebaCuzca

spring.datasource.url=jdbc:postgresql://localhost:5432/bancoCuzca
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8084

resilience4j.circuitbreaker.instances.paymentService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.paymentService.permittedNumberOfCallsInHalfOpenState=2

jwt.secret=${JWT_SECRET:MiClaveSecretaSuperSeguraParaElBanco2026!#}
jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.prefix=${JWT_PREFIX:Bearer}
jwt.header=${JWT_HEADER:Authorization}